export enum MenuItemId {
  SERVER = 'server',
  DEBUG = 'debug',
  DISCONNECT_SERVER = 'disconnect-server',
  ADD_INSTANCE = 'add-instance',
  START_ALL_INSTANCES = 'start-all-instances',
  STOP_ALL_INSTANCES = 'stop-all-instances',
  MANAGE = 'manage',
  TOOLS = 'tools',
  TUNNEL = 'tunnel',
  TUNNEL_ENABLE = 'tunnel-enable',
  TUNNEL_DISABLE = 'tunnel-disable',
  HELP = 'help',
  ABOUT_US = 'about-us',
  DOCUMENT = 'document',
  EXIT = 'exit',
}
